### ISSUE TITLE
Port 8081

### ISSUE THREAD

**Issue by elminster13** [ChrisRomp/addon-ecowitt-proxy#10]
I dont think the port override in the configuration is working. I have installed version 0.1.17 and changed the configured port to be 4199 as I was getting a conflict with the opentread rest api port which is also 8081, so I think anyone with a skyconnect installed in their home assistant yellow will have this issue.
![image](https://github.com/ChrisRomp/addon-ecowitt-proxy/assets/85672917/eec3d05c-a69b-49bc-ad41-c772c0c685ae)

now when i start up the add-on i can see the following error in the logs:

`s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[18:27:01] INFO: Using webhook ID xxxxxxxxxxxxxxx
Address in use
Port 8081 is in use by another program. Either identify and stop that program, or start the server with a different port.
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped`

I stopped the silicon labs multiprotocol add-on and fired up your one and all is good so thank you for that but i thought I would report the issue with the port mapping anyway.

**Comment by ChrisRomp** [comment]
I overlooked the fact that with local networking the TCP port mapping doesn't really do anything. So, I've moved the configuration out of networking and into the general configuration.
