### ISSUE TITLE
HA API Error: 404: Not Found

### ISSUE THREAD

**Issue by Clueless-tech** [ChrisRomp/addon-ecowitt-proxy#17]
@ChrisRomp

Ecowitt Proxy does not forward data to Ecowitt Integration. 
No devices or entitets are discovered.

Log is spammed with HA API ERROR: 404. Can you please have a look at this.

![bild](https://github.com/ChrisRomp/addon-ecowitt-proxy/assets/72553805/6014145b-a5d1-4b68-8f81-7c3c501653e5)
![bild](https://github.com/ChrisRomp/addon-ecowitt-proxy/assets/72553805/d0e4510b-4751-4c6e-86c2-619eeb499bc4)
![bild](https://github.com/ChrisRomp/addon-ecowitt-proxy/assets/72553805/be30a1a2-9ac9-4ae2-b163-975e8b8e7ef9)
![bild](https://github.com/ChrisRomp/addon-ecowitt-proxy/assets/72553805/c891a639-33c5-4e43-85e4-6e4af4f4d77a)

**Comment by StevenGFX** [comment]
I'm having this same issue.

**Comment by ChrisRomp** [comment]
Can you (both) provide some details on your Home Assistant setup? Are you running in Docker, HA Yellow, Raspberry Pi, etc.?  Just curious about things I can try to reproduce the error.

The 404 is kind of weird because it will be using the API between containers, so I'm wondering what's different.

**Comment by StevenGFX** [comment]
Hey @ChrisRomp, Thanks for the reply. I can add a little bit of context, but I'm not sure exactly what you need, but will follow up with any request. I'm using HA Yellow. My Internal/External URLs are the same (home.foodomain.com).

**Comment by ChrisRomp** [comment]
I'll do some experimenting soon to try and reproduce the issue. I'm also running HA Yellow but I'm a release or two behind.

**Comment by Clueless-tech** [comment]
Hi @ChrisRomp,

I'm running HA on Raspberry Pi. 

I also forgot to mention that I'm using the integrated Ecowitt integration. Not the one in HACS. Does the proxy support both?
https://www.home-assistant.io/integrations/ecowitt

--
Core 2023.11.0
Supervisor 2023.10.1
Operating System 11.1
Frontend 20231030.1

**Comment by StevenGFX** [comment]
I'm using the intergated one as well.

**Comment by Clueless-tech** [comment]
@ChrisRomp 

Have you been able to reproduce the error?

**Comment by StevenGFX** [comment]
I had a chance to look at this again this evening and realized we both copied the webhook path (/api/webhook/[webhook_id]) instead of the Webhook ID itself. 🤦🏻 Sending a post request now give me 200. However, my Ecowitt integration status doesn't change and doesn't discover any devices/entities.

**Comment by Clueless-tech** [comment]
@StevenGFX 
Aha! You are 100% correct. Changed from /api/webhook/*webhookID* to only webhookID. It works great now, the Ecowitt integration found the device and all its entities.

**Comment by ChrisRomp** [comment]
Thank you both for working it out. I was at a conference this week so hadn't yet had a chance to dig in. Glad it was something that simple.
