### ISSUE TITLE
Change default port from 8081 (conflicts with HA's Thread Border router)

### ISSUE THREAD

**Issue by Coder84619** [ChrisRomp/addon-ecowitt-proxy#24]
The default port that this proxy uses, 8081, is hard coded into the Google Open Thread Border Router add-on. As such, you need to change the port to an unused port. In  my case I used 8082. While changing the port is easy in the Ecowitt proxy, I think the "default" port for the add-on should be changed to a non-conflicting port. The error logs in the OTBR add-on just state "port in use", but doesn't tell you what port. I had to ask on Discord what port OTBR uses, then I realized the Ecowitt proxy created a conflict.

**Comment by ChrisRomp** [comment]
I understand. When I get some time to check into it, I'll want to ensure it doesn't cause any problems for users currently using the default setting, i.e., a new default won't change their existing configuration, because that would cause problems.
