### ISSUE TITLE
After upgrade to v1.0.0 of Proxy, default port has changed.

### ISSUE THREAD

**Issue by thayerfox** [ChrisRomp/addon-ecowitt-proxy#35]
After upgrading to v1.0.0 from v0.1.18 the ecowitt integration was no longer seeing any updates from the weather station.  I noticed that the proxy configuration had changed from port 8081 to 8082.  I did not make this change.  Upon changing it back to 8081, everything was functioning again.

Was it intended to change the proxy port for this release?  I see in the changelog that the port has been changed, but it would be a good idea to add this information in the release notes as a breaking change!

**Comment by ChrisRomp** [comment]
Ah, sorry! I thought if someone already had the integration configured it wouldn't revert the default, and I tried to test it but I guess I messed that up.  Port 8081 is used by the HA border router service, which was causing conflicts for some users including myself (see #24).

I will update the release to include a note about a breaking change. Apologies.
