### ISSUE TITLE
Need manual repo install instructions

### ISSUE THREAD

**Issue by ThermoMan** [ChrisRomp/addon-ecowitt-proxy#37]
I think HA has changed something since your install instructions were written and so they no longer work for all HA installations.

Need manual repo install instructions because the button to automatically add the repo to the HA installation results in the following error message: 
`This redirect is not supported by your Home Assistant installation. It needs either the Home Assistant Operating System or Home Assistant Supervised installation method. For more information, see the documentation.`

And that linked documentation (https://www.home-assistant.io/installation - not your problem) does not have instructions to manually install anything.

(My use case is using the Ecowitt Integration for a local, non-cloud, installation of the ambient Weather Station - I am sent to your proxy install by the instructions at https://www.derekseaman.com/2023/12/home-assistant-ecowitt-weather-station-setup.html )

**Comment by ChrisRomp** [comment]
The redirect still works on my HA instance. Not sure what's up with the link, but I agree having some manual steps wouldn't be a bad thing.

**Comment by ThermoMan** [comment]
Alas.  The docker version of Home Assistant has no Add On link under Settings.

If I copy the receiver.py file into a directory can I just launch it?  My understanding is that this receives the data in whatever format the hardware vendors ships it and reformats it for HA.  and it either holds it for HA to pick up (polling) or pushes it into HA.  So I may have some configuration variables to set.

**Comment by ChrisRomp** [comment]
Ah, I see. Yes, you could run `receiver.py` standalone or you could build another Docker image from most of what I have here.  In fact I just ran receiver.py as a service on my server before deciding to make it more shareable, since it seemed to be a common pain point for many users.

The `receiver.py` can be much simpler:

```python
from flask import Flask, request
import requests

app = Flask(__name__)

forward_url = "https://your-ha-server/api/webhook/hook-id-from-ecowitt-integration"

@app.route('/')
def version():
    return "Stub v0.1\n"

# 'application/x-www-form-urlencoded'
@app.route('/log/ha', methods=['POST'])
def logHomeAssistant():
    # Get request querystring
    payload = request.form

    # Uncomment to log payload to console
    # print("Payload: " + payload)

    response = requests.post(forward_url, data=payload)
    
    # log response to console
    response_text = response.text
    print("Response: " + response_text)

    return response_text

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8088, debug=True)
```

Don't forget to install your dependencies:

```bash
pip install flask requests
```

And if you want to install it as a service with `systemd` (e.g., Debian/Ubuntu):

```ini
[Unit]
Description=Ecowitt Proxy
After=multi-user.target
[Service]
Type=simple
Restart=always
ExecStart=/usr/bin/python3 /home/chris/dev/ecowitt-receiver/receiver.py
[Install]
WantedBy=multi-user.target
```

Here's a helpful [blog post](https://medium.com/@benmorel/creating-a-linux-service-with-systemd-611b5c8b91d6) someone wrote about creating `systemd` services on Linux which has more detail.

**Comment by ChrisRomp** [comment]
You could also run Nginx in a Docker container and configure it to just forward `POST` traffic to Home Assistant.

**Comment by ThermoMan** [comment]
I already have Apache running on that machine and am trying to learn how to use the proxy there.  But Im running into a stone wall.  Mostly I don't know where to find the error logs on HA.

On HA I have installed
1. Ecowitt
2. HACS
3. Through HACS I have installed Ambient Weather Station - Local
4. Then I have set up the proxy (see below).  I'm not limiting the proxy to POST, I just forward it all.  (My router, server, and proxy IP firewalls keep the other traffic out.)
If it's all working I'm expecting Ecowitt to populate an entity when the Weather station begins to report in. **Is this assumption correct?**

The IP address of my weather station is: `192.168.0.150`

Here is my Weather Station setup.
![Untitled](https://github.com/user-attachments/assets/eb59161e-9362-40b3-b1a2-2d57e4f0c59e)

The IP address of my HA install is `192.168.0.206` - this also where the Apache server and proxy live.

I'm running a firewall on that server and have a hole poked in it: `sudo ufw allow from 192.168.0.150 to any port 9090 proto tcp comment 'Open web port for Weather Station Proxy'`

```
<VirtualHost *:9090>
    ProxyRequests Off
    ProxyPreserveHost On
    #ServerName EcowittProxy
    ProxyPass        "/" "https://192.168.0.206:8123/api/webhook/8684ac60cb7a948dc11fa6fd252b4c9c/"
    ProxyPassReverse "/" "https://192.168.0.206:8123/api/webhook/8684ac60cb7a948dc11fa6fd252b4c9c/"
    ErrorLog ${APACHE_LOG_DIR}/WeatherProxyerror.log
    CustomLog ${APACHE_LOG_DIR}/WeatherProxyaccess.log combined
    #<Location />
     # Require ip 192.168.0.150
    #</Location>
</VirtualHost>
```

I did a test with another proxy pointing to another website on the same server and tested it from my laptop.  And was able to see that the proxy arrangement works.

**I guess I'm looking for a pointer on where to stick my nose next to find internal logging or on a step I've overlooked** (I didn't remember the firewall until yesterday - so I know it's easy to miss things. It's not the first time that the firewall has tripped me up).


If I get it all working I'll document it and post it to my original question on the HA forum.  Which has an awful title, I can fix that too perhaps?  https://community.home-assistant.io/t/what-does-i-know-that-there-are-no-add-ons-in-hacs-mean/751157

**Comment by ThermoMan** [comment]
I tried again with no ssl just to skip that last error (also as I think about it my HA does not use ssl) and although thatmakes teh ssl error go away I still get no data on my HA install.

```
192.168.0.150 - - [25/Jul/2024:19:55:00 -0500] "GET /&PASSKEY=D3301E52051523D2674A834B6C0FD163&stationtype=AMBWeatherPro_V5.1.5&dateutc=2024-07-26+00:54:59&tempf=78.4&humidity=44&windspeedmph=0.00&windgustmph=0.00&maxdailygust=0.00&winddir=331&uv=0&solarradiation=0.59&hourlyrainin=0.000&eventrainin=0.000&dailyrainin=0.000&weeklyrainin=0.000&monthlyrainin=0.012&yearlyrainin=0.012&totalrainin=0.012&battout=1&tempinf=77.9&humidityin=43&baromrelin=29.923&baromabsin=29.362 HTTP/1.1" 400 196 "-" "AMBWeatherPro"
```

**Comment by ThermoMan** [comment]
Well, I'm getting no more errors, but I don't see any data.  What should I expect to see?
